# Generated by Django 5.0.3 on 2024-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('author', models.CharField(max_length=63)),
                ('isbn', models.CharField(max_length=63)),
                ('available', models.BooleanField()),
            ],
            options={
                'ordering': ['author'],
                'indexes': [models.Index(fields=['isbn'], name='myapp_libra_isbn_572f68_idx')],
            },
        ),
    ]
